domain: "nexenta.local"

vcenter_hostname: "vcenter.nexenta.local"
vcenter_username: "Administrator@vsphere.local"
vcenter_password: "Nexenta1!"

datacenter: "SC"
cluster: "i40"
folder: "i40"
datastore: "ns-nfs2"
net_1Gbit: "1GB"
net_10Gbit: "DPortGroup"

vm_name: "fc_vm_01"

vmpref: "i40"
ha_nodes_x11:
     nef_license: ''
     nodes:
         H1:
             name: 'x11-62'
             ip1g: "10.4.100.62"
             ip10g:  "192.168.1.62"
             IPMI: "10.3.251.66"
             Q4: "62"
         H2:
             name: 'x11-63'
             ip1g: "10.4.100.63"
             ip10g:  "192.168.1.63"
             IPMI: "10.3.251.67"
             Q4: "63"
     nics: ['i40e4','i40e5']
     group_int: "aggr0"
     pools:
             tankm1: "-fM18 mirror tankm1"
             tankz2: "-NfM16 raidz2 tankz2"
     pools_cache:
             tankm1: ['c0t5000C5003017E1B3d0']
             tankz2: ['c0t5000C5003017E1FFd0']
     vips: ['192.168.100.1','192.168.100.2','192.168.100.3','192.168.100.4']
     esxs:
        esx-58: 'iqn.1998-01.com.vmware:esx-58-6cb399e5'
        esx-59: 'iqn.1998-01.com.vmware:esx-59-3cd11c6a'
     vm_net: "DPortGroup"

ha_nodes_d: "{{ ha_nodes_x11 }}"

ha_nodes: ['{{ha_nodes_d.nodes.H1.name}}','{{ha_nodes_d.nodes.H2.name}}']

#IPs
vip1: "{{ha_nodes_d.vips[0]}}" 
vip2: "{{ha_nodes_d.vips[1]}}"
vip3: "{{ha_nodes_d.vips[2]}}"
iscsi_vip: "{{ha_nodes_d.vips[3]}}"
share_ip: "{{ vip2 }}"
share_c: 256

tg_iscsi: "tg_iscsi_ans_vm_1"

#SHARES and POOLS
mountpoint: "/"
pool1: "tankm1"
pool2: "tankz2"
pool3: "tank8"
pool_for_shares: "{{ pool2 }}"
pool_iscsi: "{{ pool3 }}"

#CIFS Option
cifs_user: "admin"
cifs_passwd: "nexenta"
#cifs_share: "{{ pool_for_shares }}_smb/smb-"
cifs_share: "{{ pool_for_shares }}_cifs"
cifs_vers: "2.1"

