---
domain: "hypernexenta.corp"

vcenter_hostname: "vcenter67.hypernexenta.corp"
vcenter_username: "Administrator@vsphere.local"
vcenter_password: "Nexenta@123"
datacenter: "qa_lab"
cluster: "autoD"
folder: "firecrest"
#datastore: "autoD_firecrest"
datastore: "lst_autod"
net_1Gbit: "VM Network"
net_10Gbit: "DPortGroup"
fc_vm_name: "fc_vm_01"
vmpref: "autoD"

vendor: "NEXENTA"

MAC3: "00:57:00"
MAC4: "00:59:00"
MAC_NS-530: "00:60:30"
MAC_NS-521: "00:60:31"
MAC_firecrest: "00:60:40"
MAC_Centos7: "00:60:07"
MAC_Centos8: "00:60:08"
MAC_Ubuntu18: "00:60:18"
MAC_Ubuntu20: "00:60:20"

mut: ''
VMC: 3

#CIFS Option
cifs_user: "admin"
cifs_passwd: "nexenta"
#cifs_share: "{{ pool_for_shares }}_smb/smb-"
cifs_share: "{{ pool_for_shares }}_cifs"
cifs_vers: "2.1"
...
