---
domain: "hypernexenta.corp"

vcenter_hostname: "vcenter.hypernexenta.corp"
vcenter_username: "Administrator@vsphere.local"
vcenter_password: "Nexenta@123"
datacenter: "qa_lab"
cluster: "krd"
folder: "krd"
datastore: "ns-nfs"
net_1Gbit: "10x_1G_network"
net_10Gbit: "DPortGroup"
fc_vm_name: "fc_vm_01"
vmpref: "lst"

vendor: "NEXENTA"
...
